---
# tasks file for ansible-role-mongodb
- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - mongodb

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - mongodb
